FROM python:3.9-slim

WORKDIR /app

# Copy requirements files
COPY requirements.txt .
COPY stream_requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r stream_requirements.txt

# Copy Python scripts
COPY generate_data.py .
COPY stream_data.py .

# Make scripts executable
RUN chmod +x *.py