FROM python:3.9-slim

WORKDIR /app

# Copy requirements files
COPY Data-Sources/requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy Python scripts
COPY Data-Sources/entrypoint.sh .
COPY Data-Sources/generate_data.py .
COPY Data-Sources/stream_data.py .

# Make scripts executable
RUN chmod +x *.py