FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    netcat-openbsd \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install --no-cache-dir \
    mysql-connector-python \
    kafka-python==2.0.2 \
    minio \
    faker

COPY kafka_producer.py   .
COPY kafka_consumer.py   .
COPY entrypoint_pipeline.sh .

RUN chmod +x entrypoint_pipeline.sh

ENTRYPOINT ["./entrypoint_pipeline.sh"]
